### ISSUE TITLE
Spamfilter & Log + "Visited Output"

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Tackyou/HRK-Drop-Key-Referral-Helper#1]
Can you please add the following:

Spamfilter:
If someone posts the same text more than 3 times in a row in less than 5 seconds, automatically use the chat block function on him

Visited Output: Every 10 seconds the script sends out an "Visited: Name1, Name2, Name3" 
Also it does then hide every message containing the visitlink of these persons for 4 hours.
This way all users of the script will have a very clean chat. 

Also add a log which lists, for the user, every visited profile with visit link and timestamp.

**Comment by royvandijk06** [comment]
Nice suggestions.
I wish more people would use this script. It will benefit us all.
Share it to all your friends!

**Comment by Tackyou** [comment]
Thanks for the suggestion.
I just made it for fun and I'm little lazy right now.

The current round will end in 5 hours.
If nothing changed after that and HRK starts a new round I will update the script with the block function.

And so long, don't worry. The script will remember which referrals it clicked already and will not click them again. So spammers will not disturb the bot.

**Comment by AkumaNoTsubasa** [comment]
But they heavily get into ram usage and setting them on the automated block stops that. you could even set their links on a serverside (e.g. pastebin if u dont have a hoster) list and have them blocked from the script for everyone making them sad

**Comment by Tackyou** [comment]
So as you see was not worth the time. They removed the whole system.
